### ISSUE TITLE
propose: adding exception handler

### ISSUE THREAD

**Issue by crhdev** [LordSimal/cakephp-scheduler#12]
Hi! 
I was playing a little with the scheduler, it works great for small projects. 
An improvement I should have implemented was exception handling when a command fails. Could something like this be integrated?

https://github.com/crhdev/cakephp-scheduler/blob/crhdev-patch-exception_handler/src/Command/ScheduleRunCommand.php#L52

**Comment by LordSimal** [comment]
yes, this would be a good idea.
I am just not sure if using the event system to react to exceptions is the correct way here... gotta have to think about that.
