### ISSUE TITLE
propose: Allow execute functions

### ISSUE THREAD

**Issue by crhdev** [LordSimal/cakephp-scheduler#13]
Hello, in this commit: https://github.com/crhdev/cakephp-scheduler/commit/83b584123a7cd5412eb47060671180028aeb2278 , I was playing a little to be able to allow the execution of functions instead of cake command. In my application, I have some use cases where creating a command is unnecessary. Do you think it may be possible to integrate something like this?

```
    public function schedule(Scheduler &$scheduler): void
    {
        $scheduler->execute(function($a, $b, $c, ConsoleIo $io) {
            $io->info('Sum');
            return $a + $b + $c;
        }, [1,2,3])->everyXMinutes(1);
    }
```

**Comment by LordSimal** [comment]
So you don't test these kind of functions?

I don't really like breaking this kind of structure since commands are really easy to make via `bin/cake bake command` and thats it.

Especially since all that Command class needs to have is the `execute` method. You can just remove the `buildOptionParser` method if you don't need it.

**Comment by crhdev** [comment]
Sorry, the example I gave was basic.
Maybe something like:
```
 public function schedule(Scheduler &$scheduler): void
    {
        $scheduler->execute(function($a, $b, $c, ConsoleIo $io) {
            $service = new CriticalRenewAuditLog();
            return $service->run($a, $b, $c);
        }, [1,2,3])->everyXMinutes(1);
    }
```
In this case, we have a test for CriticalRenewAuditLog class.

For some security reasons (that I don't know), in my team, it is not allowed to create cake commands for certain things since they could be invoked by other parts of the development team, for example the 'system administrators', since they can log in the container/server/whatever and execute them by hand with ./bin/cake etc...
